import 'package:covid_app/models/wilaya.dart';

const MONTHS = <String>[
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aou","Sep", "Oct", "Nov", "Dec"
];
const WILAYAS = <Wilaya>[
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "CHLEF", number: 2),
  Wilaya(name: "LAGHOUAT", number: 3),
  Wilaya(name: "OUM EL BOUAGHI", number: 4),
  Wilaya(name: "BATNA", number: 5),
  Wilaya(name: "BEJAIA", number: 6),
  Wilaya(name: "BISKRA", number: 7),
  Wilaya(name: "BECHAR", number: 8),
  Wilaya(name: "BLIDA", number: 9),
  Wilaya(name: "BOUIRA", number: 10),
  Wilaya(name: "TAMANRASSET", number: 11),
  Wilaya(name: "TÉBESSA", number: 12),
  Wilaya(name: "TELEMCEN", number: 13),
  Wilaya(name: "TIARET", number: 14),
  Wilaya(name: "TIZI OUZOU", number: 15),
  Wilaya(name: "ALGIERS", number: 16),
   Wilaya(name:"DJELFA", number: 17),
  Wilaya(name: "JIJEL", number: 18),
  Wilaya(name: "SÉTIF", number: 19),
  Wilaya(name: "SAIDA", number: 20),
  Wilaya(name: "SKIKDA", number: 21),
  Wilaya(name: "SIDI BELABBES", number: 22),
  Wilaya(name: "ANNABA", number: 23),
  Wilaya(name: "GUELMA", number: 24),
  Wilaya(name: "CONSTANTINE", number: 25),
  Wilaya(name: "MÉDÉA", number: 26),
  Wilaya(name: "MOSTAGANEM", number: 27),
  Wilaya(name: "M'SILA", number: 28),
  Wilaya(name: "MASSACRE", number: 29),
  Wilaya(name: "OURGLA", number: 30),
  Wilaya(name: "ORAN", number: 31),
  Wilaya(name: "EL BAYADH", number: 32),
   Wilaya(name: "ILLIZI", number: 33),
  Wilaya(name: "BORJ BOU ARRERIJ", number: 34),
  Wilaya(name: "BOUMÉRDES", number: 35),
  Wilaya(name: "EL TARF", number: 36),
  Wilaya(name: "TINDOUF", number: 37),
  Wilaya(name: "TISSEMSILT", number: 38),
  Wilaya(name: "EL OUED", number: 39),
  Wilaya(name: "KHENCHLA", number: 40),
  Wilaya(name: "SOUK AHRAS", number: 41),
  Wilaya(name: "TIPAZA", number: 42),
  Wilaya(name: "MILA", number: 43),
  Wilaya(name: "AIN DEFLA", number: 44),
  Wilaya(name: "NAAMA", number: 45),
  Wilaya(name: "AIN TIMOUCHENT", number: 46),
  Wilaya(name: "GHARDAIA", number: 47),
  Wilaya(name: "RELIZANE", number: 48),
];