import 'package:covid_app/models/wilaya.dart';

const MONTHS = <String>[
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aou","Sep", "Oct", "Nov", "Dec"
];
const WILAYAS = <Wilaya>[
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
   Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
   Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
];