import 'package:covid_app/models/wilaya.dart';

const MONTHS = <String>[
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aou","Sep", "Oct", "Nov", "Dec"
];
const WILAYAS = <Wilaya>[
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "CHLEF", number: 2),
  Wilaya(name: "LAGHOUAT", number: 3),
  Wilaya(name: "OUM EL BOUAGHI", number: 4),
  Wilaya(name: "BATNA", number: 5),
  Wilaya(name: "BEJAIA", number: 6),
  Wilaya(name: "BISKRA", number: 7),
  Wilaya(name: "BECHAR", number: 8),
  Wilaya(name: "BLIDA", number: 9),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
   Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
   Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
  Wilaya(name: "ADRAR", number: 1),
];